[site]
title = "Chenxiao Yu"
description = "Student at the University of Southern California."
favicon = "/favicon_io/favicon.ico" 
last_updated = "November 29, 2025"

[author]
name = "Chenxiao Yu"
title = "M.S. Student in Applied Data Science"
institution = "University of Southern California"
avatar = "/bio.jpg"

[social]
# Contact information

email = "cyu96374@usc.edu"
location = "Los Angeles, CA"
location_url = "https://www.google.com/maps/place/University+of+Southern+California"
location_details = [
  "Los Angeles, CA 90089"
]
google_scholar = "https://scholar.google.com/citations?user=SGe_dCwAAAAJ&hl=en"
github = "https://github.com/AiChiMoCha"
linkedin = "https://www.linkedin.com/in/chenxiao-yu-a813652a9/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Others"
type = "page"
target = "Others"
href = "/Others"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"
